# -*- coding: utf-8 -*-
"""Lession 9 - HW 13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HfwuGklvFleLQkeD2jQP68oASn3wppOi
"""

#Bài 13. Viết hàm
#        def find_x(a_list, x)
#    trả lại tất cả các vị trí mà x xuất hiện trong a_list, nếu không có thì trả lại -1

def find_x(a_list, x):
  i = 1
  for i in range(len(a_list)):
      if a_list[i] == x:
         return (f'Vị trí: {i}')


a_list = input("Nhập một chuỗi: ")
x = input(" Nhập ký tự: ")
find_x(a_list, x)