# -*- coding: utf-8 -*-
"""Lession 10 - HW 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H82zuIeFwb07tuAutCyijPWqc9KyywLt
"""

#Bài 01. Viết một chương trình để lấy ra tên class của một object?
class Xa_Hoi:
   def function(self):
      print('Xa_Hoi')


a_Xa_Hoi = Xa_Hoi()
a_Xa_Hoi.function()