# -*- coding: utf-8 -*-
"""Lession 5 - HW 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BHamn5t9p0NNgEUXUkcGx-9hS-KU8_uA
"""

#Bài 04. Viết chương trình đảo ngược từ ký tự thường sang ký tự hoa và từ ký tự hoa sang ký tự thường trong một chuỗi.
s = input('Nhập chuỗi bất kỳ: ')
print(s.upper())
print(s.lower())