# -*- coding: utf-8 -*-
"""Lession 2-HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZTCwwu1fRoo9ECxrYOdLUB4nXS7qyst
"""

# Bài tập 1

age = int(input('Nhập tuổi của bạn'))
income = float(input('Nhập thu nhập của bạn hàng năm'))
print(f'age >= 18 and income >= 2500$ is: {age >= 18 and income >= 2500}')