# -*- coding: utf-8 -*-
"""Lession 7 - HW 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14djruFkH9khqZliVUfvzuJ_UfaqKvDYS
"""

my_tuple = 1, 2, 3, 4, 5
giong = True
for i in range(len(my_tuple)):
  if i != i+1:
    giong = False
    break
print(f'{giong}')