# -*- coding: utf-8 -*-
"""Lession 7 - HW 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LAaiXOiIbwWDO36nm7YfNv99Fqhn4FB0
"""

#Bài 07: Viết chương trình kiểm tra 2 tuple có phần tử chung hay không.
tuple_1 = 12, 23, 34, 45, 56, 67, 87, 89
tuple_2 = 21, 32, 54, 65, 78, 98, 15, 50
chung = False
for i in tuple_1:
    if i in tuple_2:
        chung = True
        break
print(f"Hai tuple có phần tử chung không? {chung}")

