# -*- coding: utf-8 -*-
"""Lession 12- HW 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aokfQElqwBslAQSFBV6T4cv-bZO_nn16
"""

with open('/content/lession_12_file_text', 'w', encoding='utf-8') as f:
  f.write('this is string - line 1\n')
  f.write('this is string - line 2\n')
  f.write('this is string - line 3\n')
  f.write('this is string - line 4\n')
  f.write('this is string - line 5\n')
  f.write('this is string - line 6\n')
  f.write('this is string - line 7\n')
  f.write('this is string - line 8\n')
  f.write('this is string - line 9\n')
  f.write('this is string - line 10')

with open('/content/lession_12_file_text', 'r', encoding='utf-8') as f:
     n = int(input('Nhập:'))
     datalist = f.readlines()
     f_2 = datalist[:n]
     print(f_2)