# -*- coding: utf-8 -*-
"""Lession 7 - HW 00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11UAQ_gEvuZqFmJknbJ3PvrrK-eDKPqEl
"""

#Bài 00: Viết chương trình sinh một tuple chứa các phần tử có các kiểu dữ liệu khác nhau. Sau đó, unpack các phần tử trong một tuple.
a, b, c, d, e, f = 19, -1, 28.5, 'Hello', ['Python', 1, 2, 3], ('e', 'Pi', 'Number')
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)