# -*- coding: utf-8 -*-
"""Lession 7 - HW 12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dygZK9HK3g0aJCUkARcN5Zr2hp7OyI0Z
"""

#Bài 12. Viết chương trình để thử lại các phương thức của Set theo danh sách sau
#         set.difference_update(other_set)
#         set.intersection_update(other_set)
#         set.isdisjoint(other_set)
#         set.issubset(other_set)
#         set.issuperset(other_set)
#         set.symmetric_difference_update(other_set)

set_1 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
set_2 = {10, 9, 11, 15, 19, 13, 5, 0, 4, 20}
set_1.difference_update(set_2)
print(set_1)

set_1 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
set_2 = {10, 9, 11, 15, 19, 13, 5, 0, 4, 20}
set_1.intersection_update(set_2)
print(set_1)

set_1 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
set_2 = {10, 9, 11, 15, 19, 13, 5, 0, 4, 20}
set_1.symmetric_difference_update(set_2)
print(set_1)

set_1 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
set_2 = {10, 9, 11, 15, 19, 13, 5, 0, 4, 20}
print(set_1.isdisjoint(set_2))

set_1 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
set_2 = {10, 9, 11, 15, 19, 13, 5, 0, 4, 20}
print(set_1.issubset(set_2))

set_1 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
set_2 = {10, 9, 11, 15, 19, 13, 5, 0, 4, 20}
print(set_1.issuperset(set_2))