# -*- coding: utf-8 -*-
"""Lession 7 - HW 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1poSZMae9NZSulJpP4Hn5vMtlC1sY9mMY
"""

#Bài 02: Viết chương trình đảo ngược một tuple.
my_tuple = 19, -1, 28.5, 'Hello', ['Python', 1, 2, 3], ('e', 'Pi', 'Number')
print(my_tuple[::-1])