# -*- coding: utf-8 -*-
"""Lession 5 - HW 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-1EwHGG-PzL26YPztoEKeUEfTOvx4IAY
"""

#Bài 06. Viết chương trình
#    1. Nhập vào 1 chuỗi từ bàn phím
#    2. Nhập vào 1 ký tự từ bàn phím
#    3. Tìm và in ra tất cả các vị trí của ký tự vừa nhập trong chuỗi đã nhập

s = input('Nhập chuỗi: ')
sub = input('Nhập ký tự: ')
print(s.count(sub))