# -*- coding: utf-8 -*-
"""Lession 9 - HW 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EtNEs0cgukz9jW4vs3fY50Y-YxptMSTK
"""

#Bài 07. Viết hàm
#        def body_mass_index(m, h)
#    để tính toán chỉ số BMI của một người với cân nặng m (kg), chiều cao h (m)
#      Viết hàm
#        def bmi_information(m, h)
#    để đưa ra thông tin về chỉ số BMI cũng như phân loại mức độ gầy - béo của người cân nặng m, chiều cao h

def body_mass_index(m, h):
   BMI = m/(h**2)
   return BMI

m = float(input('Nhập vào cân nặng của bạn : '))
h = float(input('Nhập vào chiều cao của bạn : '))
print('BMI của bạn = ', BMI)


def bmi_information(BMI):
   if BMI < 18.5:
      return 'Bạn quá gầy'
   elif BMI <= 24.9:
      return  'Bạn bình thường'
   elif BMI <= 29.9:
      return 'Bạn hơi béo'
   elif BMI <= 34.9:
      return 'Bạn béo phì cấp độ 1'
   elif BMI <= 39.9:
      return 'Bạn béo phì cấp độ 2'
   else:
      return 'Bạn béo phì cấp độ 3'

  
print(bmi_information(BMI))