# -*- coding: utf-8 -*-
"""Lession 2 - HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TUektq6FbRF5s0bpyNO-zrKUeMTnKAAR
"""

# Bài tập 3
#TH1: a > 0, b < 0
a = 5.0
b = -3.0
chia_nguyen = a//b
chia_dư = a%b
print(chia_nguyen)
print(chia_dư)

#TH2: a < 0, b > 0
a = -9.5
b = 6.0
chia_nguyen = a//b
chia_dư = a%b
print(chia_nguyen)
print(chia_dư)

#TH3: a < 0, b < 0
a = -9.5
b = -3.5
chia_nguyen = a//b
chia_dư = a%b
print(chia_nguyen)
print(chia_dư)