# -*- coding: utf-8 -*-
"""Lession 3 - HW 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W_l5-lOD0pEC2Eb8qnXKd4oWLxaXfi-f

Bài 04. Lập trình thực hiện các công việc sau:
    1. Nhập 3 số a, b, c bất kì
    2. Hãy kiểm tra xem ba số đó có phải là độ dài của các cạnh của một tam giác hay không?
    3. Nếu đúng là tam giác thì xác định là tam giác vuông hay không?
"""

a = float(input('Nhập a ='))
b = float(input('Nhập b ='))
c = float(input('Nhập c ='))
if a+b>c and a+c>b and b+c>a:
  if a*a == b*b + c*c or b*b == a*a + c*c or c*c == a*a + b*b:
    print(f'a,b,c là 3 cạnh của tam giác vuông')
  else:
    print(f'a,b,c là 3 cạnh của tam giác không vuông')
else:
  print(f'a,b,c không phải 3 cạnh của 1 tam giác')