# -*- coding: utf-8 -*-
"""Lession 8 - HW 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qYFdh5W7hwBneabuGFJfdvklJHKZbHbd
"""

#Bài 08: Viết chương trình đếm số lần xuất hiện các từ đơn trong một đoạn văn bản
s = 'Xin chào ngày mới nắng lên ngày mới'
l = s.split()
count={}
for i in l:
    if i in count:
        count[i]+=1
    else:
        count[i]=1
for i in sorted(count, key=count.get, reverse=False):
    print(i, count[i])