# -*- coding: utf-8 -*-
"""Lession 12 - HW 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1flw0tmboynq0WSmfiroQnI-BnOxe_N5K
"""

with open('/content/lession_12_file_text', 'w', encoding='utf-8') as f:
  f.write('this is string - line 1\n')
  f.write('this is string - line 2\n')
  f.write('this is string - line 3\n')
  f.write('this is string - line 4\n')
  f.write('this is string - line 5\n')
  f.write('this is string - line 6\n')
  f.write('this is string - line 7\n')
  f.write('this is string - line 8\n')
  f.write('this is string - line 9\n')
  f.write('this is string - line 10')

#Bài 08. Viết hàm
#        def get_file_size(file)
#    để lấy và trả về dung lượng của file

import os
def get_file_size(file):
      total = os.path.getsize(file)
      return total

get_file_size('/content/lession_12_file_text')