# -*- coding: utf-8 -*-
"""Lession 6 - HW 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pUprbKXmQDU6maGCH5Klo5Ljxvgm6M2-
"""

#Bài 02. Viết chương trình tìm số lớn nhất, nhỏ nhất trong một list.
a = input('a =: ')
my_list = a.split()
print(my_list)
print(max(my_list))
print(min(my_list))

0 1 2 3 4 5 6 7 8 9 a b c d e f