# -*- coding: utf-8 -*-
"""Lession 8 - HW 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g4WX_SA0vCdD8v3-2QYChG_DU1n6_r3e
"""

#Bài 05. Viết chương trình tạo dict mới bằng cách trích xuất dữ liệu từ dict ban đầu theo tập các key cho trước
my_dict = {"name": "Kelly", "age":25, "salary": 8000, "city": "New york"}
new_dict = {}
for key, value in my_dict.items():
  if key == "name" or key == "salary":
    new_dict.update({key: value})
    print(new_dict)