# -*- coding: utf-8 -*-
"""Lession 8 - HW 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rPOiUoWppgkjinrX3-I0Fvqt7MeluepS
"""

#Bài 01. Viết chương trình tìm giá trị lớn nhất và giá trị nhỏ nhất trong các value của dict
a = {
    1: 5,
    2: 15,
    3: 8,
    4: 25,
    5: 55
}
maxx = max(a.values())
minn = min(a.values())
print(maxx)
print(minn)