# -*- coding: utf-8 -*-
"""Lession 9 - HW 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDPgaN635obzqzIY_kVOcrvT8k1XSxN6
"""

#Bài 01. Viết hàm
#        def max_min(*numbers)
#    trả lại cả giá trị max, min của nhiều số được truyền vào

def max_min(*numbers):
   return max(numbers)


x = max_min(15, 25, 45, 79, 63, 52, 2)
print(x)
def max_min(*numbers):
   return min(numbers)
   

x = max_min(15, 25, 45, 79, 63, 52, 2)
print(x)