# -*- coding: utf-8 -*-
"""Lession 3 - HW 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-1cyqwEsQTxBm_Aa3lNwZRuW660YyUu
"""

# Bài tập 3:Lập chương trình thực hiện các công việc sau:
#    1. Nhập 1 số nguyên dương n bất kì (n<1000). Yêu cầu kiểm tra dữ liệu đầu vào, nếu sai yêu cầu nhập lại.
#    2. Tính tổng các chữ số của số đó.
#    3. Hiển thị kết qủa ra màn hinh

n = int(input('Nhập n ='))
sum_n = 0
i = 0
for i in range(n+1):
  sum_n = sum_n + i
  print(f'Tổng các số nguyên dương = {sum_n}')