# -*- coding: utf-8 -*-
"""Lession 7 - HW 9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vJGOUi7K9UmJGr2XW0OMFs2jX6ql5V-x
"""

#Bài 09: Viết chương trình tính tổng và tìm giá trị lớn nhất trong tuple chứa các số thực.
my_tuple = 12.8, 23.1, 34.2, 45.3, 95.4, 56.0, 67.9, 87.3, 89.5
tong = 0
for item in my_tuple:
    tong += item

print(f"Tổng = {tong}")

print(max(my_tuple))