# -*- coding: utf-8 -*-
"""Lession 6 - HW 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xpxDZf_gkWaJMvOKLzcSIK-YQF_fejwm
"""

#Bài 07. Viết chương trình kiểm tra 2 list có phần tử chung hay không.

a = input('a = ').split()
b = input('b = ').split()
for i in a:
  if i in b:
    print(f'Phần tử chung là: {i}')
  else:
    print('Không có phần tử chung')