# -*- coding: utf-8 -*-
"""Lession 8 - HW 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KEwzLJnzBcyEvhFZ08ilMtbu-4TwXVJ1
"""

#Bài 03. Viết chương trình tạo ra dict với lớn hơn 3 phần tử,
# value của mỗi phần tử là một list có lớn hơn 5 phần tử. 
#Truy cập và in ra phần tử thứ 5 trong phần value của mỗi phần tử trong dict

a = {
    1: [1, 2, 3, 4, 5, 6],
    2: [7, 8, 9, 10, 11, 12],
    3: [13, 14, 15, 16, 17, 18],
    4: [19, 20, 21, 22, 23 ,24]
}
for key in a:
  print(f'{key}: {a[key][5]}')