# -*- coding: utf-8 -*-
"""Lession 6 - HW 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OnDAvUHTt_f5lobhhs85lDnGFf81CPST
"""

#Bài 03. Viết chương trình tạo ra list mới bằng cách ghép một chuỗi s vào các phần tử list cũ.
a = input('a =: ')
my_list = a.split()
b = input('b = ')
new_list = [i+b for i in my_list]
print(new_list)