# -*- coding: utf-8 -*-
"""Lession 7 - HW 06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1shGoj8q261c-JBZr__uyIM52lSlXTDlu
"""

#Bài 06: Viết chương trình in ra phần tử thứ 4 và phần tử thứ 4 từ cuối lên trong một tuple.
my_tuple = 19, -1, 28.5, 'Hello', ['Python', 1, 2, 3], ('e', 'Pi', 'Number')
print(my_tuple[3])
print(my_tuple[-4])