# -*- coding: utf-8 -*-
"""Lession 6 - HW 10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o9r-KZ9-wXILghyNP0-k4alggKpe9KSX
"""

#Bài 10:
A = input('A = ').split()
my_list = []
for i in A:
  if i not in my_list:
    my_list.append(i)
print(my_list)