# -*- coding: utf-8 -*-
"""Lession 8 - HW 00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQvpM4127kfd5496wa0yWk7tG-XRtt3o
"""

#Bài 00. Viết chương trình tính tích value của các phần tử trong một dict
a = {
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5
}
b = a.values()
tich = 1
for i in b:
    tich *= i
print(f'Tích các value = {tich}')