# -*- coding: utf-8 -*-
"""Lession 9 - HW 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XDJ8S4M0v-mAzOlCcPtm4znvVq5RGmGS
"""

#Bài 03. Viết hàm
#        def is_perfect(n)
#    để kiểm tra xem số tự nhiên n có phải là số hoàn hảo hay ko, trả lại True nếu có, False nếu không.

def is_perfect(n):
  tong = 0
  for i in range(1, n):
    if n % i == 0:
      tong += i
  if tong == n:
    return True
  else:
    return False


print(is_perfect(28))