# -*- coding: utf-8 -*-
"""Lession 7 - HW 11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nndq3_Z7H2uIHbc3VyUnU8w3c7Y6l6Sv
"""

#Bài 11: Viết chương trình tìm từ dài nhất trong một câu nhập vào từ bàn phím.
s = input('Nhập chuỗi: ')
Tu_Dai_Nhat = ''
Danh_Sach = s.split()
for tu in Danh_Sach:
  if len(tu) > len(Tu_Dai_Nhat):
    Tu_Dai_Nhat = tu

print({Tu_Dai_Nhat})