# -*- coding: utf-8 -*-
"""Lession 7 - HW 10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qTIDH9hGaHqw4gFHwKsbAjDjFjAZWWSC
"""

#Bài 10: Cho list sau: ["www.hust.edu.vn", "www.wikipedia.org", "www.asp.net", "www.amazon.com"]. 
#Viết chương trình để in ra hậu tố (vn, org, net, com) trong các tên miền website trong list trên.
my_list = ["www.hust.edu.vn", "www.wikipedia.org", "www.asp.net", "www.amazon.com"]
print(my_list[0][-2:])
print(my_list[1][-3:])
print(my_list[2][-3:])
print(my_list[-1][-3:])