# -*- coding: utf-8 -*-
"""Lession 6 - HW 00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F0Zm17ev1kmspONS9nsXqLj3cQwulJBW
"""

#Bài 00. Viết chương trình sinh list mới bằng cách lấy ngẫu nhiên 5 phần tử từ list gốc.
import random
A = input('Nhập chuỗi: ').split()
B = random.sample(A, 5)
print(B)