# -*- coding: utf-8 -*-
"""Lession 6 - HW 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SFEpY5fFgLWe54WX2p-LuhfLgk7mzzqJ
"""

#Bài 04. Viết chương trình chia một list thành 2 phần với độ dài phần đầu được nhập vào từ bàn phím.
A = input('Nhập chuỗi: ').split()
i = len(A)//2
print(i)
A_1 = A[:i]
A_2 = A[i:]
print(A_1)
print(A_2)