# -*- coding: utf-8 -*-
"""Lession 5 - HW 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RtHjYCX4hvTIohksKK6nPox9MFmQVdgh
"""

#Bài 03. Viết chương trình tìm ra ký tự lớn nhất và ký tự nhỏ nhất của một chuỗi nhập từ bán phím.
s = input('Chuỗi bất kỳ: ')
print(max(s))
print(min(s))