# -*- coding: utf-8 -*-
"""Lession 5 - HW 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fyx95T3hxVV6eeE_84Ufa-azerUbeM8u
"""

s = input('Nhập chuỗi = ')
print(s.replace(s[0], '$'))