# -*- coding: utf-8 -*-
"""Lession 10 - HW 00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16HbUxEKGt38m1fnwuJflb-KnVYMQco97
"""

#Bài 00. Mô phỏng lại trò chơi sau: 
#- Người chơi tung 2 con xúc xắc 6 mặt, các mặt có số chấm là: 1, 2, 3, 4, 5, 6
#- Quan sát kết quả, tính tổng các mặt hướng lên sau khi 2 con xúc xắc đứng yên
#- Lần đầu tiên,
#    - Nếu tổng là 7 hoặc 11 => Người chơi THẮNG
#    - Nếu tổng là 2, 3 hoặc 12 => Người chơi THUA
#    - Nếu tổng là 4, 5, 6, 8, 9 hoặc 10 => Đây sẽ là ĐIỂM của người chơi, và sang vòng tiếp theo
#- Để giành được THẮNG, người chơi tiếp tục tung 2 con xúc xắc cho đến khi ra được tổng = ĐIỂM trong lần đầu tiên; 
#nếu tung ra được tổng = 7 => Người chơi THUA

import random
n = int(input('Số lần muốn tung: '))
for roll in range(n):
   num_1 = random.randrange(1, 7)
   num_2 = random.randrange(1, 7)

   if num_1 + num_2 == 7 or num_1 + num_2 == 11:
      print('Win')

   elif num_1 + num_2 == 2 or num_1 + num_2 == 3 or num_1 + num_2 == 12:
      print('Lose')

   else:
      if num_1 + num_2 == 7:
         print('Lose')
      else:
         print('Win')