# -*- coding: utf-8 -*-
"""Lession 3 - HW 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AiRMF1lfoPsioQkqUVmCXF_Svwj6UCTd

Bài 05. Lập chương trình thực hiện các công việc sau:
    1. Nhập số epsilon < 1 từ bàn phím
    2. Tính e = 1 + 1/1! + 1/2! + ... + 1/n! quá trình dừng khi 1/n! < epsilon.
    3. Đưa kết quả ra màn hình
"""

import math
epsilon = float(input('Nhập epsilon < 1 ='))
e = 1
i = 1
while True:
  if 1/math.factorial(i) < epsilon:
    break
  else:
    e = e + 1/math.factorial(i)
    i += 1

print(f'Tổng = {e}')