# -*- coding: utf-8 -*-
"""Lession 9 - HW 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14hitBqED6ytyELt1fqpPCOlrTmb93vPl
"""

#Bài 08. Viết hàm
#        def change_upper_lower(str)
#    chuyển toàn bộ các ký tự in hoa sang in thường và in thường thành in hoa trong str

def change_upper_lower(str):
   s_new = str.swapcase()
   return s_new


str = input('Nhập chuỗi:')
change_upper_lower(str)
print(s_new)