# -*- coding: utf-8 -*-
"""Lession 7 - HW 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-I6iT8pBrzPXqNQROnr7-8JX6aoQUoJ_
"""

data = [(6, 2, 3), (5, 3, 1), (4, 1, 2), (7, 8, 9)]
decorated = [(tup[-1], tup) for tup in data]
decorated.sort()
print(decorated)