# -*- coding: utf-8 -*-
"""Lession 7 - HW 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m-REhRJ6LcatQqFBZ8PfnWlA2bTeD1cX
"""

#Bài 01: Viết chương trình chuyển một tuple sang thành list và ngược lại từ list sang tuple
my_tuple = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

#Chuyển tuple --> list:
my_list = list(my_tuple)
print(my_list)

#Chuyển list --> tuple:
your_tuple = tuple(my_list)
print(your_tuple)