# -*- coding: utf-8 -*-
"""Lession 12 - HW 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zu-y7OmT0ieYJwzaTesfgAdih9ZLMN3M
"""

with open('/content/lession_12_file_text', 'w', encoding='utf-8') as f:
  f.write('this is string - line 1\n')
  f.write('this is string - line 2\n')
  f.write('this is string - line 3\n')
  f.write('this is string - line 4\n')
  f.write('this is string - line 5\n')
  f.write('this is string - line 6\n')
  f.write('this is string - line 7\n')
  f.write('this is string - line 8\n')
  f.write('this is string - line 9\n')
  f.write('this is string - line 10')

#Bài 06. Viết chương trình thêm một chuỗi nào đó vào cuối file
with open('/content/lession_12_file_text', 'a', encoding='utf-8') as f:
     f.write('Hello Python! How are you?')